[package]
edition = "2024"
name    = "embers"
publish = false
version = "0.1.0"

[[bin]]
name = "generate_schema"
path = "src/generate_schema.rs"

[[bin]]
name = "embers"
path = "src/main.rs"

[dependencies]
aes-gcm            = { version = "0.10", features = ["std", "zeroize"] }
anyhow             = { version = "1.0", features = ["std"] }
askama             = { version = "0.14" }
atrium-api         = { version = "0.25" }
atrium-xrpc-client = { version = "0.5", default-features = false, features = ["reqwest"] }
bon                = { version = "3.8" }
chrono             = { version = "0.4", features = ["serde"] }
derive_more        = { version = "2.0", features = ["full"] }
figment            = { version = "0.10", features = ["env"] }
firefly-client     = { path = "../firefly-client" }
futures            = { version = "0.3" }
graphl-parser      = { git = "https://github.com/F1R3FLY-io/graphl-parser", tag = "0.0.28" }
hex                = { version = "0.4" }
poem               = { version = "3.1", features = ["anyhow", "compression", "requestid"] }
poem-openapi       = { version = "5.1", features = ["chrono", "swagger-ui", "websocket"] }
prost              = { version = "0.14" }
secp256k1          = { version = "0.31", features = ["hashes", "rand", "serde"] }
serde              = { version = "1.0", features = ["derive"] }
serde_json         = { version = "1.0" }
structural-convert = { version = "0.13" }
thiserror          = { version = "2.0" }
tokio              = { version = "1.48", features = ["macros", "rt-multi-thread", "signal"] }
tracing            = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid               = { version = "1.18", features = ["serde", "v7"] }

[lints.clippy]
cast_possible_wrap    = "allow"
cast_sign_loss        = "allow"
default_trait_access  = "allow"
ignored_unit_patterns = "allow"
implicit_hasher       = "allow"
match_same_arms       = "allow"
missing_errors_doc    = "allow"
must_use_candidate    = "allow"
needless_for_each     = "allow"
too_many_lines        = "allow"

[lints.clippy.pedantic]
level    = "warn"
priority = -1

[lints.clippy.nursery]
level    = "warn"
priority = -1
