services:
  firefly:
    image: f1r3flyindustries/f1r3fly-scala-node:latest
    pull_policy: always
    user: root
    env_file:
      - .env
    ports:
      - 14401:40401 # deploy service
      - 14402:40402 # propose service
      - 14403:40403 # rest api
    volumes:
      - ./mainnet/genesis:/var/lib/rnode/genesis
      - ./certs/node.key.pem:/var/lib/rnode/node.key.pem:ro
      - ./certs/node.certificate.pem:/var/lib/rnode/node.certificate.pem:ro
    command:
      - run
      - -s
      - --validator-private-key=6a786ec387aff99fcce1bd6faa35916bfad3686d5c98e90a89f77670f535607c
      - --host=firefly
      - --no-upnp
      - --allow-private-addresses
      - --synchrony-constraint-threshold=0.0
      - --protocol-port=40400
      - --discovery-port=40404
      - --tls-key-path=/var/lib/rnode/node.key.pem
      - --tls-certificate-path=/var/lib/rnode/node.certificate.pem

  firefly-read:
    image: f1r3flyindustries/f1r3fly-scala-node:latest
    pull_policy: always
    user: root
    ports:
      - 14413:40403 # rest api
    command:
      - run
      - --bootstrap=rnode://ebffd419dea60220734ccea8875e86d87bac10a7@firefly?protocol=40400&discovery=40404
      - --host=firefly-read
      - --no-upnp
      - --allow-private-addresses

  firefly-testnet:
    image: f1r3flyindustries/f1r3fly-scala-node:latest
    pull_policy: always
    user: root
    ports:
      - 15401:40401 # deploy service
      - 15402:40402 # propose service
      - 15403:40403 # rest api
    volumes:
      - ./testnet/genesis:/var/lib/rnode/genesis
      - ./certs/node.key.pem:/var/lib/rnode/node.key.pem:ro
      - ./certs/node.certificate.pem:/var/lib/rnode/node.certificate.pem:ro
    command:
      - run
      - -s
      - --validator-private-key=6a786ec387aff99fcce1bd6faa35916bfad3686d5c98e90a89f77670f535607c
      - --host=firefly-testnet
      - --no-upnp
      - --allow-private-addresses
      - --synchrony-constraint-threshold=0.0
      - --protocol-port=40400
      - --discovery-port=40404
      - --tls-key-path=/var/lib/rnode/node.key.pem
      - --tls-certificate-path=/var/lib/rnode/node.certificate.pem

  firefly-read-testnet:
    image: f1r3flyindustries/f1r3fly-scala-node:latest
    pull_policy: always
    user: root
    ports:
      - 15413:40403 # rest api
    command:
      - run
      - --bootstrap=rnode://ebffd419dea60220734ccea8875e86d87bac10a7@firefly-testnet?protocol=40400&discovery=40404
      - --host=firefly-read-testnet
      - --no-upnp
      - --allow-private-addresses

  state-sync-init:
    build:
      context: ..
      dockerfile: docker/state-sync.dockerfile
      args:
        POSTGRESQL_VERSION: 17
    depends_on:
      firefly:
        condition: service_healthy
    restart: "no"
    profiles:
      - state-sync
    command:
      - --wallet-key=232DADA5BBAFC0799D5F370DA04AF70CE438F69F954512B26D6FB5B560B81DFE
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - init

  state-sync:
    build:
      context: ..
      dockerfile: docker/state-sync.dockerfile
      args:
        POSTGRESQL_VERSION: 17
    depends_on:
      firefly:
        condition: service_healthy
      state-sync-init:
        condition: service_completed_successfully
    profiles:
      - state-sync
    command:
      - --wallet-key=232DADA5BBAFC0799D5F370DA04AF70CE438F69F954512B26D6FB5B560B81DFE
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - upload
      - --db-url=postgresql://postgres@postgresql:5432
      - --interval=300

  events-init:
    build:
      context: ..
      dockerfile: docker/events-sync.dockerfile
    depends_on:
      firefly:
        condition: service_healthy
    restart: "no"
    profiles:
      - multiple-networks
    command:
      - --wallet-key=232DADA5BBAFC0799D5F370DA04AF70CE438F69F954512B26D6FB5B560B81DFE
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - init

  events-listen:
    build:
      context: ..
      dockerfile: docker/events-sync.dockerfile
    depends_on:
      firefly:
        condition: service_healthy
      events-init:
        condition: service_completed_successfully
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 2683:2683
    profiles:
      - multiple-networks
    command:
      - --wallet-key=232DADA5BBAFC0799D5F370DA04AF70CE438F69F954512B26D6FB5B560B81DFE
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - listen
      - --communication-service-api-addr=0.0.0.0:8082
      - --sync-api-addr=0.0.0.0:2683
      - --external-hostname=events-listen
      - --extra-sources=ws://host.docker.internal:2999/xrpc/com.atproto.sync.subscribeRepos

  events-push:
    build:
      context: ..
      dockerfile: docker/events-sync.dockerfile
    depends_on:
      firefly:
        condition: service_healthy
      events-init:
        condition: service_completed_successfully
    extra_hosts:
      - host.docker.internal:host-gateway
    profiles:
      - multiple-networks
    command:
      - --wallet-key=232DADA5BBAFC0799D5F370DA04AF70CE438F69F954512B26D6FB5B560B81DFE
      - --deploy-service-url=http://firefly:40401
      - --propose-service-url=http://firefly:40402
      - --service-id=docker-pds
      - push
      - --events-source-url=ws://host.docker.internal:2583/xrpc/com.atproto.sync.subscribeRepos
      - --time-threshold=3
      - --size-threshold=16
