[package]
edition = "2024"
name    = "events-sync"
publish = false
version = "0.1.0"

[dependencies]
anyhow            = { version = "1.0" }
async-stream      = { version = "0.3" }
base64            = { version = "0.22" }
bitcode           = { version = "0.6", features = ["serde"] }
clap              = { version = "4.5", features = ["derive"] }
firefly-client    = { path = "../firefly-client" }
futures           = { version = "0.3" }
hex               = { version = "0.4" }
scopeguard        = { version = "1.2" }
secp256k1         = { version = "0.31", features = ["hashes"] }
serde             = { version = "1.0", features = ["derive"] }
serde_json        = { version = "1.0" }
tokio             = { version = "1.48", features = ["macros", "rt-multi-thread", "signal", "sync"] }
tokio-stream      = { version = "0.1" }
tokio-tungstenite = { version = "0.28" }
tonic             = { version = "0.14" }
uuid              = { version = "1.18", features = ["v4"] }
warp              = { version = "0.4", features = ["server", "websocket"] }

[lints.clippy]
cast_possible_wrap    = "allow"
cast_sign_loss        = "allow"
default_trait_access  = "allow"
ignored_unit_patterns = "allow"
implicit_hasher       = "allow"
match_same_arms       = "allow"
missing_errors_doc    = "allow"
must_use_candidate    = "allow"
needless_for_each     = "allow"
too_many_lines        = "allow"

[lints.clippy.pedantic]
level    = "warn"
priority = -1

[lints.clippy.nursery]
level    = "warn"
priority = -1
